function [agumented_image] = agument_image(image)
%AUMENT_IMAGE Summary of this function goes here
augmentation = imageDataAugmenter(...
    'RandRotation', [0, 360],...
    'RandScale', [0.5, 1],...
    'RandXReflection', true,....
    'RandYReflection', true,...
    'RandXShear', [0, 25],...
    'RandYShear', [0, 25],...
    'RandXTranslation', [0 15],...
    'RandYTranslation', [0 15]);
agumented_image = augment(augmentation, image);
end

